version: '3.9'

services:
  mongo:
    image: mongo:7
    container_name: rag_mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    networks:
      - rag_net

  qdrant:
    image: qdrant/qdrant:v1.7.0
    container_name: rag_qdrant
    ports:
      - '6333:6333'
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - rag_net

  redis:
    image: redis:7-alpine
    container_name: rag_redis
    ports:
      - '6379:6379'
    networks:
      - rag_net

volumes:
  mongo_data:
  qdrant_data:

networks:
  rag_net:
    driver: bridge
